# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/vga_constrs.xdc

# IP: ip/rom1/rom1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom1 || ORIG_REF_NAME==rom1}]
