# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/helmutresch/WorkDir/VHDL_VGA_controller/impl/VGA_controller.cache/wt [current_project]
set_property parent.project_path /home/helmutresch/WorkDir/VHDL_VGA_controller/impl/VGA_controller.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
add_files /home/helmutresch/WorkDir/VHDL_VGA_controller/images/Testbild_320x240.coe
add_files /home/helmutresch/WorkDir/VHDL_VGA_controller/images/SpaceInvader_100x100.coe
add_files -quiet /home/helmutresch/WorkDir/VHDL_VGA_controller/generate/rom1/rom1/rom1.dcp
set_property used_in_implementation false [get_files /home/helmutresch/WorkDir/VHDL_VGA_controller/generate/rom1/rom1/rom1.dcp]
add_files -quiet /home/helmutresch/WorkDir/VHDL_VGA_controller/generate/rom2/rom2/rom2.dcp
set_property used_in_implementation false [get_files /home/helmutresch/WorkDir/VHDL_VGA_controller/generate/rom2/rom2/rom2.dcp]
read_vhdl -library xil_defaultlib {
  /home/helmutresch/WorkDir/VHDL_VGA_controller/vhdl/sourcemultiplexer_.vhd
  /home/helmutresch/WorkDir/VHDL_VGA_controller/vhdl/memory2_.vhd
  /home/helmutresch/WorkDir/VHDL_VGA_controller/vhdl/memory1_.vhd
  /home/helmutresch/WorkDir/VHDL_VGA_controller/vhdl/pattern2_.vhd
  /home/helmutresch/WorkDir/VHDL_VGA_controller/vhdl/iologic_.vhd
  /home/helmutresch/WorkDir/VHDL_VGA_controller/vhdl/prescaler_.vhd
  /home/helmutresch/WorkDir/VHDL_VGA_controller/vhdl/pattern1_.vhd
  /home/helmutresch/WorkDir/VHDL_VGA_controller/vhdl/vgacontroller_.vhd
  /home/helmutresch/WorkDir/VHDL_VGA_controller/vhdl/sourcemultiplexer_rtl.vhd
  /home/helmutresch/WorkDir/VHDL_VGA_controller/vhdl/memory2_rtl.vhd
  /home/helmutresch/WorkDir/VHDL_VGA_controller/vhdl/iologic_rtl.vhd
  /home/helmutresch/WorkDir/VHDL_VGA_controller/vhdl/top_VGA_.vhd
  /home/helmutresch/WorkDir/VHDL_VGA_controller/vhdl/vgacontroller_rtl.vhd
  /home/helmutresch/WorkDir/VHDL_VGA_controller/vhdl/pattern2_rtl.vhd
  /home/helmutresch/WorkDir/VHDL_VGA_controller/vhdl/pattern1_rtl.vhd
  /home/helmutresch/WorkDir/VHDL_VGA_controller/vhdl/prescaler_rtl.vhd
  /home/helmutresch/WorkDir/VHDL_VGA_controller/vhdl/memory1_rtl.vhd
  /home/helmutresch/WorkDir/VHDL_VGA_controller/vhdl/top_VGA_rtl.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/helmutresch/WorkDir/VHDL_VGA_controller/impl/VGA_controller.srcs/constrs_1/new/vga_constrs.xdc
set_property used_in_implementation false [get_files /home/helmutresch/WorkDir/VHDL_VGA_controller/impl/VGA_controller.srcs/constrs_1/new/vga_constrs.xdc]


synth_design -top top_VGA -part xc7a35tcpg236-1


write_checkpoint -force -noxdef top_VGA.dcp

catch { report_utilization -file top_VGA_utilization_synth.rpt -pb top_VGA_utilization_synth.pb }
